name: Push components to Espressif Component Service

on:
  push:
    tags:
      - v*

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "mipi_dsi_abstraction"
          version: ${{ github.ref_name }}
          namespace: "nicolaielectronics"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
